### ISSUE TITLE
Dependency cycle after update to 8.4.0

### ISSUE THREAD

**Issue by dhs-rec** [puppetlabs/puppetlabs-apt#1036]
## Describe the Bug
After updating the module from 8.3.0 to 8.4.0, I get a dependency cycle on all Debian family nodes, for any repo I manage:
```
Found 1 dependency cycle:
(Exec[apt_update] => Class[Apt::Update] => Package[gnupg] => Apt::Key[Add key: 5B7C3E5A735BCB4D615829DC0BDDA991FD7AAC8A from Apt::Source theforman_buster] => Apt::Setting[list-theforman_buster] => File[/etc/apt/sources.list.d/theforman_buster.list] => Class[Apt::Update] => Exec[apt_update])\nTry the '--graph' option and opening the resulting '.dot' file in OmniGraffle or GraphViz
```

## Expected Behavior
No dependency cycle.

## Steps to Reproduce
1. Update the module
2. Start an agent run

## Environment
 - Version 8.4.0
 - Platform Debian 10 / Ubuntu 20.04

## Additional Context
- After adding back the lines
```
  # required for adding GPG keys on Debian 9 (and derivatives)
  ensure_packages(['gnupg'])
```
in `init.pp` the cycle was gone.
- I do all the repository setup in a separate Puppet stage, executed before the `main` stage.

**Comment by tlebars** [comment]
Same issue here.

Reverting #1020 as suggested by @dhs-rec fixed it.

**Comment by david22swan** [comment]
@dhs-rec @tlebars 
Hey, have put a pr up for this issue if you'd like to take a look and possibly pull it down onto one of your machines to check that it fixes the issue:
https://github.com/puppetlabs/puppetlabs-apt/pull/1039

**Comment by dhs-rec** [comment]
@david22swan, I replaced my workaround with your fix and it's still working.

**Comment by david22swan** [comment]
That's it merged and a release has been cut so it should be good now.
