### ISSUE TITLE
How to change the contents of sources.list

### ISSUE THREAD

**Issue by iamsumesh** [puppetlabs/puppetlabs-apt#1041]
Please explain the steps to change the contents of sources.list

**Comment by jamesps-ebi** [comment]
I would also like to know this. If it's possible to modify the content of sources.list directly (instead of placing drop-in files under sources.list.d), I can't see any relevant instructions in the documentation.

**Comment by chelnak** [comment]
Hello!

This behaviour is something that is not supported by this module.

You could potentially achieve this by using the `File` resource.

Thanks!
