### ISSUE TITLE
Ubuntu packages may contain dot

### ISSUE THREAD

**Issue by xepa** [puppetlabs/puppetlabs-apt#1074]
## Describe the Bug
```
apt::mark { 'containerd.io': setting => 'hold' }
```

## Expected Behavior
Package should be held (this is a regression)

## Steps to Reproduce
Mark any package containing a . in the package name

## Environment
 - puppet-agent  6.28.0-1jammy
 - Ubuntu 22.04

## Additional Context
there are some other packages with a . in the name.

**Comment by tinuzz** [comment]
To add to this: the regexp used in `apt::mark` is wrong on more than just the dot, for Debian and Ubuntu:

```
  if $title !~ /^[a-zA-Z0-9\-_]+$/ {
    fail("Invalid package name: ${title}")
  }
```
As per the Debian [Policy manual](https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-source):

> Package names (both source and binary) must consist only of lower case letters (a-z), digits (0-9), plus (+) and minus (-) signs, and periods (.). They must be at least two characters long and must start with an alphanumeric character.

So, the '+' and '.' are missing, and the '_' should go.

**Comment by xepa** [comment]
It might be better to refactor the regex to the following this would satisfy the title policy of Debian (and I would assume Ubuntu), just let me know and I can refactor it in the PR for this issue
```
^[a-z0-9]{2}[a-z0-9\.\-\+]*$
```

**Comment by tinuzz** [comment]
Just a small note: in a character class, the dot and the plus sign don't have to be escaped.

**Comment by xepa** [comment]
I have updated the PR to reflect the latest input of @tinuzz
