### ISSUE TITLE
validation of ppa breaks ppa

### ISSUE THREAD

**Issue by jgrammen-agilitypr** [puppetlabs/puppetlabs-apt#1084]
## Describe the Bug
#1052 introduced validation of ppa names
```
  # Validate the resource name
  if $name !~ /^ppa:([a-zA-Z0-9\-_]+)\/([a-zA-z0-9\-_]+)$/ {
    fail("Invalid PPA name: ${name}")
  }

```
But it does not seems to account for all valid ppa names
my ppa now fails
https://launchpad.net/~jason.grammenos.agility/+archive/ubuntu/php-static
```
Invalid PPA name: ppa:jason.grammenos.agility/php-static 
```

## Expected Behavior
valid ppa's should be acccepted

## Steps to Reproduce
```
  ::apt::ppa { "ppa:jason.grammenos.agility/php-static":
    notify  => Exec['apt-update'],             # Resync package index files
    require => Package['add-apt-package'],     # Ensure system can add ppa's
  }
```
notice error in output

## Environment
 - 9.0.1 
 - Ubuntu 20.04

**Comment by chelnak** [comment]
Hey @jgrammen-agilitypr - wondering if [this pr](https://github.com/puppetlabs/puppetlabs-apt/pull/1075) fixes the issue?

**Comment by jgrammen-agilitypr** [comment]
it does not appear to change the regex for ppa's, so no I do not think it does.

**Comment by jgrammen-agilitypr** [comment]
Thank you for the crazy fast fix.
correct me if I am wrong but it appears that the fix has a bug in it?

```if $name !~ /^ppa:([a-zA-Z0-9\-_.]+)\/([a-zA-z0-9\-_\.]+)$/ {```
should there not be a leading `\` in front of the added `.` just like in the second half of the regex?
ex:
```if $name !~ /^ppa:([a-zA-Z0-9\-_\.]+)\/([a-zA-z0-9\-_\.]+)$/ {```

**Comment by kenyon** [comment]
Not necessary to escape a dot in a character class.
