### ISSUE TITLE
Variables ($release) that are defined as undef are breaking with '' validation

### ISSUE THREAD

**Issue by mcka1n** [puppetlabs/puppetlabs-apt#1089]
## Describe the Bug

Martin Alfke (@tuxmea) found a bug and reached out to us at the Conf Management Conference.

The issue is that this line breaks:

https://github.com/puppetlabs/puppetlabs-apt/blob/main/templates/pin.pref.epp#L6 

https://github.com/puppetlabs/puppetlabs-apt/blob/main/manifests/pin.pp#L51

Because the variable changed to undef and the validation.

## Expected Behavior

The validation doesn't break

## Steps to Reproduce
1. Use the apt module, and try to call any of the Strings defined in the module

https://github.com/puppetlabs/puppetlabs-apt/blob/main/manifests/pin.pp#L51

<img width="563" alt="image" src="https://user-images.githubusercontent.com/1958982/217228871-eba23400-0461-4250-9c57-f33fccdb8777.png">

## Environment
 - Release 9.0.1 https://github.com/puppetlabs/puppetlabs-apt/releases/tag/v9.0.1 

## Additional Context

Martin might add more context about this bug 

@tuxmea

**Comment by tuxmea** [comment]
Reproducing the bug:

```
  include apt
  apt::pin { 'test2':
    release => 'buster',
  }
```
