### ISSUE TITLE
Switch apt::key from apt-key to trusted.gpg.d

### ISSUE THREAD

**Issue by AardvarKOlogY** [puppetlabs/puppetlabs-apt#1099]
## Use Case
From Debian 11 and Ubuntu 22.04 on, apt-key throws a deprecation warning whenever being used, as apt-key stores keys in /etc/apt/trusted.gpg altogether. The new paradigm tells us to use separate files in /etc/apt/trusted.gpg.d/*.gpg.
Also, apt update on Ubuntu 22.04 also now throws warnings whenever somebody or something, e.g. our apt::key, continues to manage apt keys in that very file.

## Describe the Solution You Would Like
Change apt::key to populate files in /etc/apt/trusted.gpg.d (e.g. <title>.gpg), which should be treated as keyrings with one or multiple keys inside.

## Describe Alternatives You've Considered
Continuing the module as is so far as long as we only get deprecation *warnings*.

**Comment by kenyon** [comment]
I think this is a duplicate of #1034.

**Comment by AardvarKOlogY** [comment]
Duplicate is correct. Feature request can be closed.
