### ISSUE TITLE
apt_key can not deal with options

### ISSUE THREAD

**Issue by tuxmea** [puppetlabs/puppetlabs-apt#1102]
## Describe the Bug
We want to use the apt_key resource type using source and we want to provide proxy options.

## Expected Behavior
Proxy is used

## Environment
 - Version PE 2021.7.1 - Puppet 7
 - Platform Ubuntu 20

## Additional Context
see https://github.com/puppetlabs/puppetlabs-apt/blob/main/lib/puppet/provider/apt_key/apt_key.rb#L194
This if statement matches only if source and content are both nil.
If either one is set the options will not be added to the command.

**Comment by kenyon** [comment]
Looks the same as #1037.

**Comment by tuxmea** [comment]
duplicate of #1037
