### ISSUE TITLE
W: --force-yes is deprecated, use one of the options starting with --allow instead.

### ISSUE THREAD

**Issue by XSpielinbox** [puppetlabs/puppetlabs-apt#1130]
## Describe the Bug
Puppet calls `apt-get` with the `--force-yes` option. This option has been deprecated and replaced by `--allow-unauthenticated`, `--allow-downgrades`, `--allow-remove-essential` and `--allow-change-held-packages` in apt 1.1 in 2015.

## Expected Behavior
The Puppet apt module does not use `--force-yes`.

## Steps to Reproduce
1. run `puppet agent -t` on a node that then has to downgrade a package.

## Environment
 - Version 9.0.2
 - Platform: tested on Ubuntu 20.04 (should be the same in Ubuntu 16.04, Ubuntu 18.04 and Ubuntu 22.04 as well as all versions of Debian since at least Debian 10)

## Additional Context
For enhanced backwards compatibility one might have an option that users that really need it, can explicitly enable to use the old `--force-yes` option.

**Comment by kenyon** [comment]
The only place I see `--force-yes` in this module is here, which is in the acceptance tests, not in code that Puppet would run: https://github.com/puppetlabs/puppetlabs-apt/blob/a6db503562693ed622b2aec7ca1afb21a1ce5668/spec/acceptance/apt_spec.rb#L51

I think you want to file this bug against puppet itself, not this apt module: https://github.com/search?q=repo%3Apuppetlabs%2Fpuppet%20--force-yes&type=code

**Comment by Ramesh7** [comment]
Thanks @XSpielinbox for raising and sorry for inconvenience, looks the README.md file still points to the old JIRA URL. I have created tracker ticket internally to update to new JIRA ticket.
Will update once this activity is done. Thanks again.

Also will review the module where ever there is `--force-yes` is get used, and do needful baed on the outcome.

**Comment by Ramesh7** [comment]
Have reviewed the module and as @kenyon mentioned we only have `--force-yes` in spec file otherwise we are not using this anymore. I will also use this issue to fix that part as long run.
Thanks @kenyon for being on top of this.
