### ISSUE TITLE
repos are mandatory, though they should not be

### ISSUE THREAD

**Issue by XSpielinbox** [puppetlabs/puppetlabs-apt#1132]
## Describe the Bug
When looking at [source.pp](https://github.com/puppetlabs/puppetlabs-apt/blob/main/manifests/source.pp) one can see that if one leaves out the `repos` definition or specifies `undef`, instead of not adding a component to the sources entry, `main` is added, resulting in problems when combined with and absolute suite. When I don't specify a `repos` (so a component), there shall not be a component. At least there should be an option to end the source definition after the `release` (so the distribution).

## Expected Behavior
An apt source may only have a distribution (release in puppet) of `/` that is not followed by anything except a newline and I am able to easily replicate that with Puppet.

## Steps to Reproduce
1. Try to add a source with `[...] <url (location)> /`

## Environment
 - Version 9.0.2
 - Platform tested on Ubuntu 20.04 (should be the same on all other version of Ubuntu and Debian)

## Additional Context
There is a workaround when specifying a `repos` of `''`, though that does not work in all cases. see #1133

**Comment by Ramesh7** [comment]
Closing this as we have covered implementation in #1138
