### ISSUE TITLE
Puppet produces invalid list of sources that it cannot correct anymore

### ISSUE THREAD

**Issue by XSpielinbox** [puppetlabs/puppetlabs-apt#1133]
## Describe the Bug
Leaving out the `repos` in an `apt::source` definition results in a `main` component being added implicitly. This however can result in an invalid apt-source when the release is `/`:
When there is apt-source with the content like `deb https://pkgs.k8s.io/core:/stable:/v1.28/deb / main`, this is invalid (absolute Suite Component).
When now working around this by defining
```
release => '/',
repos    => '',
```
this however still results in an error like the following:
```
Error: Could not prefetch package provider 'apt': Execution of '/usr/bin/apt-mark showmanual' returned 100: E: Malformed entry 3 in list file /etc/apt/sources.list.d/kubernetes.list (absolute Suite Component)
E: The list of sources could not be read.
Error: Failed to apply catalog: Execution of '/usr/bin/apt-mark showmanual' returned 100: E: Malformed entry 3 in list file /etc/apt/sources.list.d/kubernetes.list (absolute Suite Component)
E: The list of sources could not be read.
```
So puppet was able to successfully add the `main` component to the source but is unable to remove it again. One has to manually edit the corresponding source entry to something different before puppet will change it again.

## Expected Behavior
Puppet is in all cases able to correct the error in an apt source definition.

## Steps to Reproduce
1. run `puppet agent -t` with an `apt::source`, that does not specify `repos`. // alternatively add it manually to the source
2. change the `apt::source` to a `repos` `''`.
3. try to rerun `puppet agent -t`

## Environment
 - Version 9.0.2
 - Platform: tested on Ubuntu 20.04 (should be the same on all other version of Ubuntu and Debian)

## Additional Context
This makes it impossible to workaround the issue, that Puppet enforces to specify a `repos` (components), even though they are optional in an apt source. see #1132

**Comment by Ramesh7** [comment]
Hi @XSpielinbox, Thanks for raising and also providing the reproducing steps, using that I was able to repro the same.
I have raised the same internally and will priorities and get back here. 
Thanks again !!

**Comment by Ramesh7** [comment]
Hi @XSpielinbox, I have raised [PR](https://github.com/puppetlabs/puppetlabs-apt/pull/1138)  to better handing the $repos and $release, can you please review and suggest if it covers the expectation or please suggest changes if any. 
Thanks

**Comment by Ramesh7** [comment]
@XSpielinbox wanted to know more detail around this problem, AFAIK the https://github.com/puppetlabs/puppetlabs-apt/pull/1138 should put a workaround as $repos either its passed from user or not based on $release it will form source list and update. Even though the $repos assigned to default if user is not passing or user explicitly passes it.

**Comment by Ramesh7** [comment]
Thanks for detailed explanation @XSpielinbox, based on my understanding the puppet internally doing `sha256` to guarantees the state of file is into desired state which I have observed working file while working on apt source list. I have manually modified as well as via code and it was able to bring into desired state without any issues.
Can you please provide with reproduce steps so that I can re-pro and take it forward?

**Comment by kenyon** [comment]
Best thing to do is create an acceptance test which causes the problem, then write the code to fix the test failures. Then there is less room for interpretation and error.
