### ISSUE TITLE
apt::ppa not adding a ppa repository which was previously removed or purged

### ISSUE THREAD

**Issue by eyeeyeeye** [puppetlabs/puppetlabs-apt#160]
Attempting to ensure the latest collectd 5 on Ubuntu 12.04 with PE3.

If ppa:raravena80/collectd5 has never been added, the following will add the repo on a puppet run:

```
  apt::ppa { 'ppa:raravena80/collectd5': }

  package { 'collectd':
    ensure  => latest,
    require => Apt::Ppa['ppa:raravena80/collectd5'],
  }
```

If you then issue 

`add-apt-repository --remove ppa:raravena80/collectd5`
or
`ppa-purge ppa:raravena80/collectd5`

subsequent puppet runs will not add the repo.

This occurs because ppa files remain in /etc/apt/sources.list.d/, causing puppet to assume the ppa is currently added, even though the ppa has been removed.

Troubleshooting:
Run `puppet agent -t`, see that the ppa repo is added, collectd 5 is installed.
Remove or purge the ppa repo, remove collectd 5.
Run `puppet agent -t`, see that the ppa repo is not added, collectd 4 is installed.
Remove collectd 4, then remove /etc/apt/sources.list.d/raravena80-collectd5\* and /etc/apt/sources.list.d/.raravena80-collectd5*.
Run `puppet agent -t`, see that the ppa repo is added, collectd 5 is installed.

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
