### ISSUE TITLE
Need a better way to implement "apt mirrors"

### ISSUE THREAD

**Issue by LinguineCode** [puppetlabs/puppetlabs-apt#165]
Hey puppetlabs,

I have a feature request for your module. My DC hosts their own apt mirror and it would be cool to have your module set it. I have found a way to do it using Hiera, but it's a bit cumbersome. I think it would be better having something like "apt::mirror"

relevant code from hiera.yaml:

```
...
:hierarchy:
- location/%{::customfact_location}-%{::lsbdistcodename}
- common
```

relevant code from /etc/puppet/hieradata/location/myDCcompany-precise.yaml

```

---
apt::purge_sources_list: true
apt::purge_sources_list_d: true
apt::source:
 'ubuntu':
  location:     'http://mirror.myDCcompany.com/ubuntu/'
  repos:        'main restricted universe multiverse'
  include_src:  'true'
 'precise-backports':
  location:     'http://mirror.myDCcompany.com/ubuntu/'
  repos:        'main restricted universe multiverse'
  release:      'precise-backports'
 'precise-security':
  location:     'http://mirror.myDCcompany.com/ubuntu/'
  repos:        'main restricted universe multiverse'
  release:      'precise-security'
```

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
