### ISSUE TITLE
-y is not a valid option for add-apt-repository on Lucid

### ISSUE THREAD

**Issue by derikson** [puppetlabs/puppetlabs-apt#190]
On Lucid, and probably other versions of Ubuntu, -y is an invalid option. This causes use of the apt::ppa resource to fail with "Error: /usr/bin/add-apt-repository -y ppa:git-core/ppa returned 2 instead of one of [0]".

The $option parameter should only be set to "-y" by default on versions of Debian/Ubuntu that support it.

See #146, where this option was introduced.

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
