### ISSUE TITLE
Allow specification of a key source as a `puppet:///` URL

### ISSUE THREAD

**Issue by t-8ch** [puppetlabs/puppetlabs-apt#213]
We would like to keep the keys in the puppet repo and let the puppet agent fetch it from the fileserver. Example overloading `key_source`:

``` puppet
apt::key { 'jenkins':
  key        => 'D50582E6',
  key_source => 'puppet:///modules/infrastructure/jenkins.key',
}
```

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
