### ISSUE TITLE
Killing apt::force

### ISSUE THREAD

**Issue by daenney** [puppetlabs/puppetlabs-apt#233]
I was looking at `apt::force` and I want to kill it. The way it forces a package to be installed from a specific release is entirely horrible. Doing it in such a way should really be a last resort and might cause weird behaviour as policies change or newer packages start rolling in to different mirrors.

The correct way of doing this is dropping a pin/preferences file in apt that causes the policy to reflect the origin you want those packages from and then just leveraging Puppet's package type's `ensure` attribute to do the rest.

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
