### ISSUE TITLE
Wrong error message: Unsupported osfamily or lsbdistid

### ISSUE THREAD

**Issue by mgagne** [puppetlabs/puppetlabs-apt#247]
`apt::params` looks for `$::lsbdistid` and `$::lsbdistcodename`.

If any combination of those values aren't supported, catalog compilation fails with this error: `Unsupported osfamily (XXX) or lsbdistid (YYY)`

lsbdistcodename should be mentioned instead of osfamily.

Note: This bug is particularly frustrating as a new default clause as been added to the case in `apt::params`. Having a misleading error message makes debugging harder, especially for existing rspec tests in other modules which are now all suddenly failing.

Those rspec tests might not always inject those facts due to puppetlabs-apt not having a hard requirement on them before ; because OS specific configurations defined in params were only used by `apt::backports` and `apt::ppa`.

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
