### ISSUE TITLE
Anchor in apt::source::* for apt::update

### ISSUE THREAD

**Issue by olivierHa** [puppetlabs/puppetlabs-apt#252]
Hello, 

I am trying to figure out the purpose of that anchor in sources.pp :   
# Need anchor to provide containment for dependencies.

  anchor { "apt::source::${name}":
    require => Class['apt::update'],
  }

Indeed, in my manifest, I've added : 

 Apt::Source <| |> -> Exec["apt_update"]

And I got a dependency cycle : 

(Anchor[apt::source::source1] => Apt::Source[source1] => Exec[apt_update] => Class[Apt::Update] => Anchor[apt::source::source1])

I think setting all our sources before doing an apt-get update is the normal way, or am i missing something ?

Regards

Olivier

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
