### ISSUE TITLE
Error: Could not prefetch apt_key provider 'apt_key': invalid byte sequence in UTF-8

### ISSUE THREAD

**Issue by jurgenweber** [puppetlabs/puppetlabs-apt#266]
So, I have a list of keys added via

apt::keys.... This works fine.

I then added a few PPAs today using

apt::ppa { 'ppa:ondrej/php5': }
apt::ppa { 'ppa:ondrej/mysql-5.6': }

this added the key:

pub   1024R/E5267A6C 2009-01-26
uid                  Launchpad PPA for Ondřej Surý

so now every time I run puppet, I believe because of the accent characters in this persons name I am seeing the message "Error: Could not prefetch apt_key provider 'apt_key': invalid byte sequence in UTF-8" and all of the keys using apt::keys are reinstalled every time.

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
