### ISSUE TITLE
apt::backports installs contrib and non-free without asking

### ISSUE THREAD

**Issue by xaque208** [puppetlabs/puppetlabs-apt#269]
Currently, apt::backports adds the contrib and non-free sources.  If the repos are desired, the user should be able to turn them on, but this should not be the default.  Only 'main' should be the default.

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
